name: forms_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.5.0
  injectable_generator: ^2.7.0
  kt_dart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  freezed: ^3.0.6



flutter:
  uses-material-design: true
  assets:
    - assets/
